#baseURL: "https://sevenzerothree.github.io/"
languageCode: "en-us"
title: "The Programmer's Ephemeris"
sectionPagesMenu: "main"
relativeURLs: true

pygmentsCodeFences: true
pygmentsStyle: vs


params:
  isSupportEnabled: false
  isSearchEnabled: false
  isFeaturedSectionEnabled: false

menu:
  footer:
  - identifier: about
    name: About
    url: /about/
  - identifier: contact
    name: Contact
    url: /contact/
