#baseURL: "https://sevenzerothree.github.io/"
languageCode: "en-us"
title: "The Programmer's Ephemeris"
sectionPagesMenu: "main"
relativeURLs: true

pygmentsCodeFences: true
pygmentsStyle: vs

related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
  - name: keywords
    weight: 100
  - name: date
    weight: 10

params:
  isSupportEnabled: false
  isSearchEnabled: false
  isFeaturedSectionEnabled: false

menu:
  footer:
  - identifier: about
    name: About
    url: /about/
  - identifier: contact
    name: Contact
    url: /contact/
